// <auto-generated />
namespace AdvancedAccountingCustomerTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test_customerrestricitons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_customerrestricitons));
        
        string IMigrationMetadata.Id
        {
            get { return "201801060050083_test_customerrestricitons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
